name: flutter_tg_helper
description: "App that helps you get tg stats."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  rename: ^3.0.2
  tdlib:
    path: ./tg_lib
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/tg_icon.png
    
  
